version: '3.8'
services:
  n8n:
    build:
      context: .
      dockerfile: Dockerfile-debian
      args:
        - N8N_VERSION=${N8N_VERSION:-latest}
        - NVM_VERSION=${NVM_VERSION:-0.39.3}
        - NODE_VERSION=${NODE_VERSION:-20}
    restart: always
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_DATABASE=${DB_POSTGRESDB_DATABASE:-n8n}
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_USER=${DB_POSTGRESDB_USER:-n8n}
      - DB_POSTGRESDB_PASSWORD=${DB_POSTGRESDB_PASSWORD}
      - DB_POSTGRESDB_SCHEMA=public
      - N8N_PORT=${N8N_PORT:-5678}
      - N8N_PATH=${N8N_PATH:-/}
      - NODE_ENV=${NODE_ENV:-production}
      - NODE_FUNCTION_ALLOW_EXTERNAL=${NODE_FUNCTION_ALLOW_EXTERNAL:-crypto}
      - WEBHOOK_URL=${WEBHOOK_URL}
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE:-Europe/London}
      - TZ=${TZ:-Europe/London}
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
      - EXECUTIONS_DATA_PRUNE=${EXECUTIONS_DATA_PRUNE:-true}
      - EXECUTIONS_DATA_MAX_AGE=${EXECUTIONS_DATA_MAX_AGE:-336}
      - N8N_DIAGNOSTICS_ENABLED=${N8N_DIAGNOSTICS_ENABLED:-true}
      - N8N_HIRING_BANNER_ENABLED=${N8N_HIRING_BANNER_ENABLED:-false}
      - N8N_PERSONALIZATION_ENABLED=${N8N_PERSONALIZATION_ENABLED:-true}
      - N8N_METRICS=${N8N_METRICS:-true}
      - N8N_LOG_LEVEL=${N8N_LOG_LEVEL:-verbose}
      - N8N_COMMUNITY_PACKAGES_ENABLED=${N8N_COMMUNITY_PACKAGES_ENABLED:-true}
      - N8N_TEMPLATES_ENABLED=${N8N_TEMPLATES_ENABLED:-true}
      - N8N_REINSTALL_MISSING_PACKAGES=${N8N_REINSTALL_MISSING_PACKAGES:-true}
      - N8N_EDITOR_BASE_URL=${N8N_EDITOR_BASE_URL:-https://localhost:5678}
      - N8N_AI_ENABLED=${N8N_AI_ENABLED:-false}
      - N8N_AI_OPENAI_API_KEY=${N8N_AI_OPENAI_API_KEY}
      - N8N_REINSTALL_MISSING_PACKAGES=${N8N_REINSTALL_MISSING_PACKAGES:-false}
      - CODE_ENABLE_STDOUT=${CODE_ENABLE_STDOUT:-true}
      - NODE_FUNCTION_ALLOW_BUILTIN=${NODE_FUNCTION_ALLOW_BUILTIN:-*}
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium
      - CHROME_BIN=/usr/bin/chromium
      - CHROME_PATH=/usr/lib/chromium/
      - PUPPETEER_ARGS=--no-sandbox,--disable-setuid-sandbox,--disable-dev-shm-usage,--disable-gpu
    ports:
      - ":5678"
    volumes:
      - n8n_data_annex:/data
    depends_on:
      - postgres
  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_DB=${DB_POSTGRESDB_DATABASE:-n8n}
      - POSTGRES_USER=${DB_POSTGRESDB_USER:-n8n}
      - POSTGRES_PASSWORD=${DB_POSTGRESDB_PASSWORD}
    ports:
      - ":5432"
    volumes:
      - postgres_data_n8n_annex:/var/lib/postgresql/data
volumes:
  n8n_data_annex:
  postgres_data_n8n_annex:
