version: '3.8'

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:${N8N_VERSION:-latest}
    restart: always
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_DATABASE=${N8N_DB_NAME:-n8n}
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_USER=${N8N_DB_USER:-n8n}
      - DB_POSTGRESDB_PASSWORD=${N8N_DB_PASSWORD}
			- DB_POSTGRESDB_SCHEMA=public
      - N8N_HOST=${N8N_HOST:-localhost}
      - N8N_PORT=${N8N_PORT:-5678}
      - N8N_PROTOCOL=${N8N_PROTOCOL:-http}
      - N8N_PATH=${N8N_PATH:-/}
      - NODE_ENV=${NODE_ENV:-production}
			- NODE_FUNCTION_ALLOW_EXTERNAL=crypto
      - WEBHOOK_URL=${N8N_WEBHOOK_URL}
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE:-UTC}
      - TZ=${TZ:-UTC}
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
      - EXECUTIONS_DATA_PRUNE=true
      - EXECUTIONS_DATA_MAX_AGE=${EXECUTIONS_DATA_MAX_AGE:-336}
      - N8N_DIAGNOSTICS_ENABLED=${N8N_DIAGNOSTICS_ENABLED:-true}
      - N8N_HIRING_BANNER_ENABLED=false
      - N8N_PERSONALIZATION_ENABLED=${N8N_PERSONALIZATION_ENABLED:-true}
      - NODE_FUNCTION_ALLOW_EXTERNAL=${NODE_FUNCTION_ALLOW_EXTERNAL:-true}
      - SQLITE_VACUUM_ON_STARTUP=${SQLITE_VACUUM_ON_STARTUP:-true}
      - N8N_METRICS=${N8N_METRICS:-true}
			- N8N_LOG_LEVEL=verbose
	    - N8N_COMMUNITY_PACKAGES_ENABLED=true
    ports:
      - ":5678"
    volumes:
      - n8n_data_annex:/home/node/.n8n
    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_DB=${N8N_DB_NAME:-n8n}
      - POSTGRES_USER=${N8N_DB_USER:-n8n}
      - POSTGRES_PASSWORD=${N8N_DB_PASSWORD}
    volumes:
      - postgres_data_n8n_annex:/var/lib/postgresql/data

volumes:
  n8n_data_annex:
  postgres_data_n8n_annex:
